name: infra

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - run: |
          az deployment group create -g wth-github --template-file ./ARM-Templates/container-webapp-template.json