# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET - Docker

on: 
  workflow_dispatch:
  push:
    paths:
      - 'Application/**'
  pull_request:
    branches: [ "main" ]

env:
  registryName: xcwthdevopsreg.azurecr.io
  repositoryName: wth/dotnetcoreapp
  dockerFolderPath: Application/src/RazorPagesTestSample
  tag: ${{github.run_number}}

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: docker login
        run: docker login $registryName -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

      - name: docker build
        run: docker build -t $registryName/$repositoryName:$tag --build-arg build_version=$tag $dockerFolderPath

      - name: docker push
        run: docker push $registryName/$repositoryName:$tag

  deploy-dev:
    runs-on: ubuntu-latest
    needs: docker
    environment:
      name: dev
      url: https://xcwthdevops-dev.azurewebsites.net
    steps: 
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: xcwthdevops-dev
          images: ${{ env.registryName }}/wth/dotnetcoreapp:${{ env.tag }}

  deploy-test:
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment:
      name: test
      url: https://xcwthdevops-test.azurewebsites.net
    steps: 
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: xcwthdevops-test
          images: ${{ env.registryName }}/wth/dotnetcoreapp:${{ env.tag }}

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-test
    environment:
      name: prod
      url: https://xcwthdevops-prod.azurewebsites.net
    steps: 
      - name: Azure authentication
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Deploy to Azure Web App for Container'
        uses: azure/webapps-deploy@v2
        with: 
          app-name: xcwthdevops-prod
          images: ${{ env.registryName }}/wth/dotnetcoreapp:${{ env.tag }}
